# Generated by Django 6.1.2 on 2026-10-09 14:32

import common.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to=common.common.create_path),
        ),
    ]
